# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dD2atmZdRnjHQYeYECqdmDEfdRvIvOEB
"""

#1
w=float(input("enter width: "))
l=float(input("enter height: "))
area=w*l
print("area of rectangle is: ",area)

#2
w=float(input("enter weight: "))
h=float(input("enter height: "))
bmi=w/h**2
print("Body Mass Index is: ",bmi)

#3
d={'vinay':25,'sharez':30,'lokesh':50,'naveen':70}
for i,j in d.items():
  print('name:',i,'score:',d[i])

#4
age=int(input("enter age:"))
if age>0:
  if age>=18 and age<=30:
    print("adult")
  elif age<18:
    print("minor")
  else:
    print("senior")

#5
print("Even numbers between 1 and 50 are")
for i in range(0,51,2):
  print(i,end='  ')

#6
p='123'
p1=input("enter password")
while(p!=p1):
  p1=input("incorrect")
print("correct")

#7
def average(values):
  print("the average is:",sum(values)/len(values))
values=list(map(int,input("enter values by giving space after each number :").split()))
average(values)

#8
def count(string):
  vowels=['a','e','i','o','u','A','E','I','O','U']
  count=0
  for i in string:
    if i in vowels:
      count+=1
  print("Vowels count is a string  is  {}".format(count))

count("vinay")

#9
from datetime import *

today = date.today()
print("Today's date:", today)
current_time =datetime.now()

print(" current Time now  is:", current_time)

#10
def add(a,b):
    try:
      ans =a+b
      print("Addition of numbers is : {}".format(ans))
    except TypeError as error:
      print("Don't Enter different Datatype please enter numbers")
add(1,2)

#11
try:
  x = int(input("Please enter a number: "))
except ValueError:
  print("Oops!  That was not a valid number.  Try again...")

#12
def division(a,b):

  try:
    ans=a/b
    print("Ans : {}".format(ans))
  except ZeroDivisionError as error:
    print("Error : {} is not possible ".format(error))


division(5,2)

#13
from google.colab import drive
drive.mount('/content/drive')
with open("/content/drive/MyDrive/sample_for_internal.txt",'w') as file:
  file.write("Hello, Python!")
  file.close()

#14
with open('/content/drive/MyDrive/sample_for_internal.txt','r')as file:
  data=file.read()
  print(data)
  file.close()

#15
with open("/content/drive/MyDrive/sample_for_internal.txt",'a') as file:
  file.write("\n I am Vinay")

with open('/content/drive/MyDrive/sample_for_internal.txt','r')as file:
  data=file.read()
  print(data)
  file.close()