# -*- coding: utf-8 -*-
"""Internal2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Anp9hIKh6CqGBSS-qRRGJWKtTRBBtrIl
"""

#1
import numpy as np
import pandas as pd
r=np.array([[[255,0,0],[0,255,0],[0,0,255]],[[255,255,0],[255,0,255],[0,255,255]],[[127,127,127],[200,200,200],[50,50,50]]])
print(r)
print((0.2989*r[0]) + (0.5870*r[1])+(0.1140*r[2]))

#2
data=np.array([[10,20,30],[50,60,130],[15,25,50]])
print(data)
print(data[0].mean())
print(data[0].std())
print(data[1].mean())
print(data[1].std())
print(data[2].mean())
print(data[2].std())

#3sensor_data=np.array([[[1,2,3],[4,5,6],[7,8,9]],
                     [[10,11,12],[13,14,15],[16,17,18]],
                     [[19,20,21],[22,23,24],[25,26,27]]])

sensor_data.shape = (3, 3, 3)
flattened_data = [sensor.flatten() for sensor in sensor_data]
concatenated_data = np.concatenate(flattened_data)
reshaped_data = concatenated_data.reshape(sensor_data.shape[0], -1)

#4

#5
import numpy as np
arr=np.array([[1,2,3,4],[3,4,5,np.nan]])
for i in arr:
  result=np.nanmean(i[len(i)-3:len(i)])
  print(i[len(i)-3:len(i)])
  print(result)

#6

#7
data={'name':['A','B','C','D','E','F','G'],'age':[25,30,35,40,45,50,55],'city':['N','L','C','H','P','M','B'],'dept':['HR','IT','Finance','Marketing','Sales','IT','HR']}
print(pd.DataFrame(data))
filter=data[(data['age']<45 & data['dept']!='HR')][['name','city']]
print(filter)

#8

#9

#10
import pandas as pd
data={'Department':['Electronics','Electronics','Clothing','Clothing','Home Goods'],
      'Salesperson':['Alice','Bob','Charlie','David','Eve'],
      'Sales':[70000,50000,30000,40000,60000]}
df=pd.DataFrame(data)
average_sales=df.groupby(['Department','Salesperson']).mean()
print(average_sales)